[workspace]
members = ["crates/calc", "crates/store", "crates/web"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[workspace.dependencies]
argon2 = "=0.6.0"
axum = "=0.8.9"
axum-login = "=0.18.0"
console_error_panic_hook = "=0.1.7"
leptos = "=0.8.20"
leptos_axum = "=0.8.10"
rust_decimal = { version = "=1.43.0", features = ["serde"] }
serde = { version = "=1.0.228", features = ["derive"] }
sqlx = { version = "=0.8.6", default-features = false }
tokio = "=1.49.0"
tower-sessions = "=0.14.0"
tower-sessions-sqlx-store = "=0.15.0"
wasm-bindgen = "=0.2.108"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
